# Generated by Django 5.2.13 on 2026-04-15 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Negotiation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=10)),
                ('initial_offer', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negotiations_as_buyer', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negotiations', to='products.product')),
            ],
            options={
                'db_table': 'negotiations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='NegotiationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('price_offer', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('message_type', models.CharField(choices=[('TEXT', 'Text Message'), ('OFFER', 'Price Offer'), ('COUNTER', 'Counter Offer'), ('ACCEPT', 'Accept'), ('REJECT', 'Reject'), ('SYSTEM', 'System Message')], default='TEXT', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('negotiation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='negotiations.negotiation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negotiation_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'negotiation_messages',
                'ordering': ['created_at'],
            },
        ),
    ]
